# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gs_auth.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gs_auth.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rgs_auth.proto\"<\n\x19PlayerRegistrationRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x1c\n\x1aPlayerRegistrationResponse\"/\n\x0cLoginRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"a\n\rLoginResponse\x12\x0f\n\x07idToken\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08refToken\x18\x03 \x01(\t\x12\x10\n\x08loggedIn\x18\x04 \x01(\x08\x12\x0c\n\x04time\x18\x05 \x01(\x02\"\x1e\n\rLogoutRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"\x10\n\x0eLogoutResponse\"$\n\x11PlayerInfoRequest\x12\x0f\n\x07idToken\x18\x01 \x01(\t\"}\n\x12PlayerInfoResponse\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x19\n\x11passwordUpdatedAt\x18\x02 \x01(\t\x12\x15\n\remailVerified\x18\x03 \x01(\t\x12\x10\n\x08presence\x18\x04 \x01(\x08\x12\x14\n\x0clastActivity\x18\x05 \x01(\x02\"4\n!AuthenticationTokenRefreshRequest\x12\x0f\n\x07idToken\x18\x01 \x01(\t\"5\n\"AuthenticationTokenRefreshResponse\x12\x0f\n\x07idToken\x18\x01 \x01(\t\"&\n\x15UpdateActivityRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"\x18\n\x16UpdateActivityResponse2\xb4\x03\n\x18GameserverAuthentication\x12K\n\x0eRegisterPlayer\x12\x1a.PlayerRegistrationRequest\x1a\x1b.PlayerRegistrationResponse\"\x00\x12.\n\x0bLoginPlayer\x12\r.LoginRequest\x1a\x0e.LoginResponse\"\x00\x12\x31\n\x0cLogoutPlayer\x12\x0e.LogoutRequest\x1a\x0f.LogoutResponse\"\x00\x12:\n\rGetPlayerInfo\x12\x12.PlayerInfoRequest\x1a\x13.PlayerInfoResponse\"\x00\x12g\n\x1a\x41uthenticationTokenRefresh\x12\".AuthenticationTokenRefreshRequest\x1a#.AuthenticationTokenRefreshResponse\"\x00\x12\x43\n\x0eUpdateActivity\x12\x16.UpdateActivityRequest\x1a\x17.UpdateActivityResponse\"\x00\x62\x06proto3')
)




_PLAYERREGISTRATIONREQUEST = _descriptor.Descriptor(
  name='PlayerRegistrationRequest',
  full_name='PlayerRegistrationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='email', full_name='PlayerRegistrationRequest.email', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='PlayerRegistrationRequest.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=77,
)


_PLAYERREGISTRATIONRESPONSE = _descriptor.Descriptor(
  name='PlayerRegistrationResponse',
  full_name='PlayerRegistrationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=107,
)


_LOGINREQUEST = _descriptor.Descriptor(
  name='LoginRequest',
  full_name='LoginRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='email', full_name='LoginRequest.email', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='LoginRequest.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=156,
)


_LOGINRESPONSE = _descriptor.Descriptor(
  name='LoginResponse',
  full_name='LoginResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='idToken', full_name='LoginResponse.idToken', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='email', full_name='LoginResponse.email', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='refToken', full_name='LoginResponse.refToken', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='loggedIn', full_name='LoginResponse.loggedIn', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='LoginResponse.time', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=158,
  serialized_end=255,
)


_LOGOUTREQUEST = _descriptor.Descriptor(
  name='LogoutRequest',
  full_name='LogoutRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='email', full_name='LogoutRequest.email', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=257,
  serialized_end=287,
)


_LOGOUTRESPONSE = _descriptor.Descriptor(
  name='LogoutResponse',
  full_name='LogoutResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=289,
  serialized_end=305,
)


_PLAYERINFOREQUEST = _descriptor.Descriptor(
  name='PlayerInfoRequest',
  full_name='PlayerInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='idToken', full_name='PlayerInfoRequest.idToken', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=307,
  serialized_end=343,
)


_PLAYERINFORESPONSE = _descriptor.Descriptor(
  name='PlayerInfoResponse',
  full_name='PlayerInfoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='email', full_name='PlayerInfoResponse.email', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='passwordUpdatedAt', full_name='PlayerInfoResponse.passwordUpdatedAt', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='emailVerified', full_name='PlayerInfoResponse.emailVerified', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='presence', full_name='PlayerInfoResponse.presence', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lastActivity', full_name='PlayerInfoResponse.lastActivity', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=345,
  serialized_end=470,
)


_AUTHENTICATIONTOKENREFRESHREQUEST = _descriptor.Descriptor(
  name='AuthenticationTokenRefreshRequest',
  full_name='AuthenticationTokenRefreshRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='idToken', full_name='AuthenticationTokenRefreshRequest.idToken', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=472,
  serialized_end=524,
)


_AUTHENTICATIONTOKENREFRESHRESPONSE = _descriptor.Descriptor(
  name='AuthenticationTokenRefreshResponse',
  full_name='AuthenticationTokenRefreshResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='idToken', full_name='AuthenticationTokenRefreshResponse.idToken', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=526,
  serialized_end=579,
)


_UPDATEACTIVITYREQUEST = _descriptor.Descriptor(
  name='UpdateActivityRequest',
  full_name='UpdateActivityRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='email', full_name='UpdateActivityRequest.email', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=581,
  serialized_end=619,
)


_UPDATEACTIVITYRESPONSE = _descriptor.Descriptor(
  name='UpdateActivityResponse',
  full_name='UpdateActivityResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=621,
  serialized_end=645,
)

DESCRIPTOR.message_types_by_name['PlayerRegistrationRequest'] = _PLAYERREGISTRATIONREQUEST
DESCRIPTOR.message_types_by_name['PlayerRegistrationResponse'] = _PLAYERREGISTRATIONRESPONSE
DESCRIPTOR.message_types_by_name['LoginRequest'] = _LOGINREQUEST
DESCRIPTOR.message_types_by_name['LoginResponse'] = _LOGINRESPONSE
DESCRIPTOR.message_types_by_name['LogoutRequest'] = _LOGOUTREQUEST
DESCRIPTOR.message_types_by_name['LogoutResponse'] = _LOGOUTRESPONSE
DESCRIPTOR.message_types_by_name['PlayerInfoRequest'] = _PLAYERINFOREQUEST
DESCRIPTOR.message_types_by_name['PlayerInfoResponse'] = _PLAYERINFORESPONSE
DESCRIPTOR.message_types_by_name['AuthenticationTokenRefreshRequest'] = _AUTHENTICATIONTOKENREFRESHREQUEST
DESCRIPTOR.message_types_by_name['AuthenticationTokenRefreshResponse'] = _AUTHENTICATIONTOKENREFRESHRESPONSE
DESCRIPTOR.message_types_by_name['UpdateActivityRequest'] = _UPDATEACTIVITYREQUEST
DESCRIPTOR.message_types_by_name['UpdateActivityResponse'] = _UPDATEACTIVITYRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PlayerRegistrationRequest = _reflection.GeneratedProtocolMessageType('PlayerRegistrationRequest', (_message.Message,), dict(
  DESCRIPTOR = _PLAYERREGISTRATIONREQUEST,
  __module__ = 'gs_auth_pb2'
  # @@protoc_insertion_point(class_scope:PlayerRegistrationRequest)
  ))
_sym_db.RegisterMessage(PlayerRegistrationRequest)

PlayerRegistrationResponse = _reflection.GeneratedProtocolMessageType('PlayerRegistrationResponse', (_message.Message,), dict(
  DESCRIPTOR = _PLAYERREGISTRATIONRESPONSE,
  __module__ = 'gs_auth_pb2'
  # @@protoc_insertion_point(class_scope:PlayerRegistrationResponse)
  ))
_sym_db.RegisterMessage(PlayerRegistrationResponse)

LoginRequest = _reflection.GeneratedProtocolMessageType('LoginRequest', (_message.Message,), dict(
  DESCRIPTOR = _LOGINREQUEST,
  __module__ = 'gs_auth_pb2'
  # @@protoc_insertion_point(class_scope:LoginRequest)
  ))
_sym_db.RegisterMessage(LoginRequest)

LoginResponse = _reflection.GeneratedProtocolMessageType('LoginResponse', (_message.Message,), dict(
  DESCRIPTOR = _LOGINRESPONSE,
  __module__ = 'gs_auth_pb2'
  # @@protoc_insertion_point(class_scope:LoginResponse)
  ))
_sym_db.RegisterMessage(LoginResponse)

LogoutRequest = _reflection.GeneratedProtocolMessageType('LogoutRequest', (_message.Message,), dict(
  DESCRIPTOR = _LOGOUTREQUEST,
  __module__ = 'gs_auth_pb2'
  # @@protoc_insertion_point(class_scope:LogoutRequest)
  ))
_sym_db.RegisterMessage(LogoutRequest)

LogoutResponse = _reflection.GeneratedProtocolMessageType('LogoutResponse', (_message.Message,), dict(
  DESCRIPTOR = _LOGOUTRESPONSE,
  __module__ = 'gs_auth_pb2'
  # @@protoc_insertion_point(class_scope:LogoutResponse)
  ))
_sym_db.RegisterMessage(LogoutResponse)

PlayerInfoRequest = _reflection.GeneratedProtocolMessageType('PlayerInfoRequest', (_message.Message,), dict(
  DESCRIPTOR = _PLAYERINFOREQUEST,
  __module__ = 'gs_auth_pb2'
  # @@protoc_insertion_point(class_scope:PlayerInfoRequest)
  ))
_sym_db.RegisterMessage(PlayerInfoRequest)

PlayerInfoResponse = _reflection.GeneratedProtocolMessageType('PlayerInfoResponse', (_message.Message,), dict(
  DESCRIPTOR = _PLAYERINFORESPONSE,
  __module__ = 'gs_auth_pb2'
  # @@protoc_insertion_point(class_scope:PlayerInfoResponse)
  ))
_sym_db.RegisterMessage(PlayerInfoResponse)

AuthenticationTokenRefreshRequest = _reflection.GeneratedProtocolMessageType('AuthenticationTokenRefreshRequest', (_message.Message,), dict(
  DESCRIPTOR = _AUTHENTICATIONTOKENREFRESHREQUEST,
  __module__ = 'gs_auth_pb2'
  # @@protoc_insertion_point(class_scope:AuthenticationTokenRefreshRequest)
  ))
_sym_db.RegisterMessage(AuthenticationTokenRefreshRequest)

AuthenticationTokenRefreshResponse = _reflection.GeneratedProtocolMessageType('AuthenticationTokenRefreshResponse', (_message.Message,), dict(
  DESCRIPTOR = _AUTHENTICATIONTOKENREFRESHRESPONSE,
  __module__ = 'gs_auth_pb2'
  # @@protoc_insertion_point(class_scope:AuthenticationTokenRefreshResponse)
  ))
_sym_db.RegisterMessage(AuthenticationTokenRefreshResponse)

UpdateActivityRequest = _reflection.GeneratedProtocolMessageType('UpdateActivityRequest', (_message.Message,), dict(
  DESCRIPTOR = _UPDATEACTIVITYREQUEST,
  __module__ = 'gs_auth_pb2'
  # @@protoc_insertion_point(class_scope:UpdateActivityRequest)
  ))
_sym_db.RegisterMessage(UpdateActivityRequest)

UpdateActivityResponse = _reflection.GeneratedProtocolMessageType('UpdateActivityResponse', (_message.Message,), dict(
  DESCRIPTOR = _UPDATEACTIVITYRESPONSE,
  __module__ = 'gs_auth_pb2'
  # @@protoc_insertion_point(class_scope:UpdateActivityResponse)
  ))
_sym_db.RegisterMessage(UpdateActivityResponse)



_GAMESERVERAUTHENTICATION = _descriptor.ServiceDescriptor(
  name='GameserverAuthentication',
  full_name='GameserverAuthentication',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=648,
  serialized_end=1084,
  methods=[
  _descriptor.MethodDescriptor(
    name='RegisterPlayer',
    full_name='GameserverAuthentication.RegisterPlayer',
    index=0,
    containing_service=None,
    input_type=_PLAYERREGISTRATIONREQUEST,
    output_type=_PLAYERREGISTRATIONRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='LoginPlayer',
    full_name='GameserverAuthentication.LoginPlayer',
    index=1,
    containing_service=None,
    input_type=_LOGINREQUEST,
    output_type=_LOGINRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='LogoutPlayer',
    full_name='GameserverAuthentication.LogoutPlayer',
    index=2,
    containing_service=None,
    input_type=_LOGOUTREQUEST,
    output_type=_LOGOUTRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetPlayerInfo',
    full_name='GameserverAuthentication.GetPlayerInfo',
    index=3,
    containing_service=None,
    input_type=_PLAYERINFOREQUEST,
    output_type=_PLAYERINFORESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AuthenticationTokenRefresh',
    full_name='GameserverAuthentication.AuthenticationTokenRefresh',
    index=4,
    containing_service=None,
    input_type=_AUTHENTICATIONTOKENREFRESHREQUEST,
    output_type=_AUTHENTICATIONTOKENREFRESHRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateActivity',
    full_name='GameserverAuthentication.UpdateActivity',
    index=5,
    containing_service=None,
    input_type=_UPDATEACTIVITYREQUEST,
    output_type=_UPDATEACTIVITYRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GAMESERVERAUTHENTICATION)

DESCRIPTOR.services_by_name['GameserverAuthentication'] = _GAMESERVERAUTHENTICATION

# @@protoc_insertion_point(module_scope)
