# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import gs_auth_pb2 as gs__auth__pb2


class GameserverAuthenticationStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.RegisterPlayer = channel.unary_unary(
        '/GameserverAuthentication/RegisterPlayer',
        request_serializer=gs__auth__pb2.PlayerRegistrationRequest.SerializeToString,
        response_deserializer=gs__auth__pb2.PlayerRegistrationResponse.FromString,
        )
    self.LoginPlayer = channel.unary_unary(
        '/GameserverAuthentication/LoginPlayer',
        request_serializer=gs__auth__pb2.LoginRequest.SerializeToString,
        response_deserializer=gs__auth__pb2.LoginResponse.FromString,
        )
    self.LogoutPlayer = channel.unary_unary(
        '/GameserverAuthentication/LogoutPlayer',
        request_serializer=gs__auth__pb2.LogoutRequest.SerializeToString,
        response_deserializer=gs__auth__pb2.LogoutResponse.FromString,
        )
    self.GetPlayerInfo = channel.unary_unary(
        '/GameserverAuthentication/GetPlayerInfo',
        request_serializer=gs__auth__pb2.PlayerInfoRequest.SerializeToString,
        response_deserializer=gs__auth__pb2.PlayerInfoResponse.FromString,
        )
    self.AuthenticationTokenRefresh = channel.unary_unary(
        '/GameserverAuthentication/AuthenticationTokenRefresh',
        request_serializer=gs__auth__pb2.AuthenticationTokenRefreshRequest.SerializeToString,
        response_deserializer=gs__auth__pb2.AuthenticationTokenRefreshResponse.FromString,
        )
    self.UpdateActivity = channel.unary_unary(
        '/GameserverAuthentication/UpdateActivity',
        request_serializer=gs__auth__pb2.UpdateActivityRequest.SerializeToString,
        response_deserializer=gs__auth__pb2.UpdateActivityResponse.FromString,
        )


class GameserverAuthenticationServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def RegisterPlayer(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def LoginPlayer(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def LogoutPlayer(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPlayerInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AuthenticationTokenRefresh(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateActivity(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GameserverAuthenticationServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'RegisterPlayer': grpc.unary_unary_rpc_method_handler(
          servicer.RegisterPlayer,
          request_deserializer=gs__auth__pb2.PlayerRegistrationRequest.FromString,
          response_serializer=gs__auth__pb2.PlayerRegistrationResponse.SerializeToString,
      ),
      'LoginPlayer': grpc.unary_unary_rpc_method_handler(
          servicer.LoginPlayer,
          request_deserializer=gs__auth__pb2.LoginRequest.FromString,
          response_serializer=gs__auth__pb2.LoginResponse.SerializeToString,
      ),
      'LogoutPlayer': grpc.unary_unary_rpc_method_handler(
          servicer.LogoutPlayer,
          request_deserializer=gs__auth__pb2.LogoutRequest.FromString,
          response_serializer=gs__auth__pb2.LogoutResponse.SerializeToString,
      ),
      'GetPlayerInfo': grpc.unary_unary_rpc_method_handler(
          servicer.GetPlayerInfo,
          request_deserializer=gs__auth__pb2.PlayerInfoRequest.FromString,
          response_serializer=gs__auth__pb2.PlayerInfoResponse.SerializeToString,
      ),
      'AuthenticationTokenRefresh': grpc.unary_unary_rpc_method_handler(
          servicer.AuthenticationTokenRefresh,
          request_deserializer=gs__auth__pb2.AuthenticationTokenRefreshRequest.FromString,
          response_serializer=gs__auth__pb2.AuthenticationTokenRefreshResponse.SerializeToString,
      ),
      'UpdateActivity': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateActivity,
          request_deserializer=gs__auth__pb2.UpdateActivityRequest.FromString,
          response_serializer=gs__auth__pb2.UpdateActivityResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'GameserverAuthentication', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
